#include "Source/Byte.hpp"
#include "Source/Comparison.hpp"
#include "Source/EnterA.hpp"
#include "Source/EnterX.hpp"
#include "Source/Enter1.hpp"
#include "Source/Enter2.hpp"
#include <iostream>
#include "Source/Machine.hpp"
#include "Source/Memory.hpp"
#include "Source/Overflow.hpp"
#include "Source/Register.hpp"
#include "Source/Sign.hpp"
#include "Source/StoreA.hpp"
#include "Source/Word.hpp"

