#include "Source/Byte.hpp"
#include "Source/Comparison.hpp"
#include "Source/Commands/EnterA.hpp"
#include "Source/Commands/EnterX.hpp"
#include "Source/Commands/Enter1.hpp"
#include "Source/Commands/Enter2.hpp"
#include <iostream>
#include "Source/Machine.hpp"
#include "Source/Memory.hpp"
#include "Source/Overflow.hpp"
#include "Source/Register.hpp"
#include "Source/Sign.hpp"
#include "Source/Commands/StoreA.hpp"
#include "Source/Word.hpp"

